<!DOCTYPE html>
<html>
<head>
	<!--Meta-->
  	<meta charset="UTF-8">
   	<meta name="viewport" content="width=device-with, initial-scale=1.0">
  	<meta name="description" content="esto es una description">
  	<meta name="keywords" content="HTML5 CSS,JS">

 	<!--Css-->
 	<link rel="stylesheet" href="views/css/reset.css">
 	<link rel="stylesheet" href="views/css/inicio.css">
 	<!--Bootstrap-->
 	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 	<!--Tipos de letras-->
  	<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,700&display=swap" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,300;1,700&display=swap" rel="stylesheet">
  	<!--js-->
      <!--jquerry-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  	<!--Bootstrap-->
  	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 

  	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  	<script src="https://kit.fontawesome.com/9266206c89.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src='views/js/funciones.js' type='text/javascript'></script>

	
    <!--Titulo-->
  	<title>Shiny-news-Administrador</title>
</head>
<body>
	<!--Cabecera cuerpo-->
	<header id="cabecera">
             <div id='cabecera'><i class="fas fa-plus" id="mas"></i> <i class="fas fa-minus" id="menos"></i><i class="fas fa-adjust" id='tiempo'></i></div>
           <h1>Shiny-News</h1><div class='descripcion'>Ingeniería Web</div>
  </header>
	<!--Barra Navegacion-->
    <ul id="barranav" class="nav">
        <li class="nav-item">
          <a class="nav-link " href="index.php">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="noticias.php?cat=todos">Noticias</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contacto.php">Contacto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="admin.php">Administrador</a>
        </li>
    </ul>
    <!--Inicio de Sesión-->
    <section>
      <div class='container'>
          <?php 
            if($datos==0 || $datos==2 || $datos==4){
              if($datos==2)
              echo "Email  y/o contraseña incorrectos. Intente nuevamente ";
              if($datos==4){
                echo "No tiene permisos de administrador";
              }
          ?>
            <form id="formulario" method="POST" action="?action=entrar">
                <div class="form-group">
                  <label for="exampleInputEmail1">Email Address</label>
                  <input type="email" class="form-control" id="nombre" name="nombre" required="true">
                </div>
              <div class="form-group">
                  <label for="clave">Contraseña</label>
                  <input type="password" class="form-control" id="clave" name="clave" required="true">
              </div>
              <button type="submit" class="btn btn-primary">Enviar</button>
              
            </form>
            <form id="formulario2" method="POST" action="?action=registrarse">
              <input type='submit' value='Registrarse'>
            </form>
        <?php 
        }else{
          if($datos==3){ ?>
            <!--Administrador-->
            <div><p>Bienvenido Administrador</p></div>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page"><a href='#'>Crear Noticia</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href='?action=Leer'>Listar/Modificar/Eliminar Noticias</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href='?action=listarContactos'>Listar Contactos</a></li>
              </ol>
            </nav>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page"><a href='?action=crearCategoria'>Crear Categoría</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href='?action=leerCategoria'>Listar/Modificar/Eliminar Categorías</a></li>
              </ol>
            </nav>
            <form id="formulario" method="POST" action="?action=crear">
              <?php if($insertar==true) echo "Noticia creada exitosamente"; ?>

              <div class="form-group">
                <label for="titulo">Título</label>
                <input type='text' class='form-control' id='titulo' name='titulo' required='true'> 

              </div>
              <div class="form-group">
                <label for="titulo">Autor</label>
                <input type="text" class="form-control" id="autor" name="autor" required="true">
              </div>
              <div class="form-group">
                  <label for="categoria">Categoría</label>
                  <select class="custom-select" name="categoria" id="categoria">
                    <option selected>Seleccione Categoría</option>
                    <?php
                      foreach($categorias as $categoria){
                        echo "<option value='".$categoria["categoria"]."'>".$categoria["categoria"]."</option>";
                      }
                    ?>
                  </select> 
              </div>
              <div class="form-group">
                  <label for="estado">Estado</label>
                  <select class="custom-select" name="estado" id="estado">
                    <option selected>Seleccione Estado</option>
                    <?php
                      echo "<option value='0'>Público</option>"; 
                      echo "<option value='1'>No Público</option>"; 
                      echo "<option value='2'>Privado</option>"; 
                    ?>
                  </select> 
              </div>
              <div class="form-group">
                <label for="texto">Texto</label>
                  <textarea type='text' class="form-control" id="noticia" name="noticia" rows="10" cols="50" required="true"></textarea>                        
              </div>
              <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
            <li class="breadcrumb-item" aria-current="page"><a href='?action=cerrar'>Cerrar Sesión</a></li>

          
        <?php     } ?>
              

      <?php } ?>
      </div>
    </section>  
	<!--Seccion Ultimas 5 Noticias-->
 
    
      
    
</body>
<!--Pie de pagina-->
<footer id="pie">
 	Copyright @2020
 	<br/>
 	ShiShiGanG
</footer>
</html>