<!DOCTYPE html>
<html>
<head>
	<!--Meta-->
  	<meta charset="UTF-8">
   	<meta name="viewport" content="width=device-with, initial-scale=1.0">
  	<meta name="description" content="esto es una description">
  	<meta name="keywords" content="HTML5 CSS,JS">

 	<!--Css-->
 	<link rel="stylesheet" href="views/css/reset.css">
 	<link rel="stylesheet" href="views/css/inicio.css">
 	<!--Bootstrap-->
 	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 	<!--Tipos de letras-->
  	<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,700&display=swap" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,300;1,700&display=swap" rel="stylesheet">
  	<!--js-->
  	<!--Bootstrap-->
  	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  	<!--jquerry-->
 	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

  	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  	<script src="https://kit.fontawesome.com/9266206c89.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src='views/js/funciones.js' type='text/javascript'></script>
    
    <!--Titulo-->
  	<title>Shiny-news-Administrador</title>
</head>
<body>
	<!--Cabecera cuerpo-->
	<header id="cabecera">
             <div id='cabecera'><i class="fas fa-plus" id="mas"></i> <i class="fas fa-minus" id="menos"></i><i class="fas fa-adjust" id='tiempo'></i></div>
           <h1>Shiny-News</h1><div class='descripcion'>Ingeniería Web</div>
  </header>
	<!--Barra Navegacion-->
  <ul id="barranav" class="nav">
      <li class="nav-item">
        <a class="nav-link " href="index.php">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="noticias.php?cat=todos">Noticias</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contacto.php">Contacto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="admin.php">Administrador</a>
      </li>
  </ul>  
  <!--CRUD-->
  <section>
    <div class='container'>
      <div><p>Bienvenido Administrador</p></div>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href='admin.php'>Crear Noticia</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href='?action=Leer'>Listar/Modificar/Eliminar Noticias</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href='?action=listarContactos'>Listar Contactos</a></li>
        </ol>
      </nav>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href='?action=crearCategoria'>Crear Categoría</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href='?action=leerCategoria'>Listar/Modificar/Eliminar Categorías</a></li>
        </ol>
      </nav>
      <!--Leer Noticia-->
      <?php if($CRUD=="Leer"){ 
        foreach ($arreglonoticias as $noticia) { ?>
          <article>
            <header id='noticia'>
              <h2><?php
                echo $noticia["titulo"]?>
              </h2>
                <div><?php   
                  $autor=$noticia["autor"]; 
                  $cate=$noticia["categoria"];?><?php 
                  echo "<a> $autor </a>" ?>  | <?php 
                  echo "<a> $cate </a>" ?> |  <?php 
                  echo $noticia["fecha"]." <br>"; ?>
                </div>
            </header>
            <p><?php
              $noticia["noticia"]=substr($noticia["noticia"],0,300);           
              echo $noticia["noticia"]."..."."<br>";?>    
            </p>
            <footer id='pieNota'>  
              <form method="POST" action='?action=modificar'>  
                <?php
                  $id=$noticia["id"];
                  echo "<input type='hidden' name='id' id='id' value=$id>";
                  echo "<input type='submit' value='Modificar' >" ?> 
              </form>
              <form method="POST" action='?action=Eliminar'>  
                <?php $id=$noticia["id"]; 
                  echo "<input type='hidden' name='id' id='id' value=$id>";
                  echo "<input type='submit' value='Eliminar'>"; ?> 
              </form>
              <form method="POST" action='?action=comentarios'>  
                <?php $id=$noticia["id"]; 
                  echo "<input type='hidden' name='id' id='id' value=$id>";
                  echo "<input type='submit' value='Comentarios'>"; ?> 
              </form>
            </footer>
          </article><?php }} ?>


      <!--Modificar-->
      <?php if($CRUD=="Modificar"){ ?>
          <form id="formulario" method="POST" action="?action=enviar">
            <div class="form-group">
              <label for="titulo">Título</label>
              <?php echo "<input type='text' class='form-control' id='titulo' name='titulo' required='true' value='".$noti["titulo"]."'>"; ?>
            </div>
            <div class="form-group">
              <label for="titulo">Autor</label>
              <?php echo "<input type='text' class='form-control' id='autor' name='autor' required='true' value='".$noti["autor"]."'>"; ?>
            </div>
            <div class="form-group">
                <label for="categoria">Categoría</label>
                <select class="custom-select" name="categoria" id="categoria">
                  <?php echo "<option selected >".$noti["categoria"]."</option>";
                    foreach($categorias as $categoria){
                      echo "<option value='".$categoria["categoria"]."'>".$categoria["categoria"]."</option>";
                    }
                  ?>
                </select> 
            </div>
            <div class="form-group">
                <label for="estado">Estado</label>
                <select class="custom-select" name="estado" id="estado">
                  <?php 
                    if($noti["estado"]==0){
                      $state="Público";
                      }else{
                        if($noti["estado"]==1){
                          $state="No Público";
                        }else{
                          if($noti["estado"]==2){
                            $state="Privado";
                          }
                        }
                      } 
                      echo "<option value='".$noti["estado"]."' selected>".$state."</option>"; 
                      echo "<option value='0'>Público</option>"; 
                      echo "<option value='1'>No Público</option>"; 
                      echo "<option value='2'>Privado</option>"; 
                  ?>
                </select> 
            </div>
            <div class="form-group">
              <label for="texto">Texto</label>
                <?php echo "<textarea type='text' class='form-control' id='noticia' name='noticia' rows='10' cols='50' required='true'>".$noti["noticia"]."</textarea>"; ?>                        
            </div>
            <?php
            $id=$noti["id"];
            echo "<input type='hidden' name='id' id='id' value=$id>";
            echo "<input type='submit' value='Enviar' >"; ?>
          </form>
      <?php } ?>    

      <!--comentarios-->
      <?php if($CRUD=="comentarios"){ ?>
        <?php 
          foreach ($comentarios as $comentario) {?>
            <article class="text-center"> 
              <?php  
                $autorNegrita=$comentario["autor"];
                echo "<b>$autorNegrita</b>";  
                echo ": ".$comentario["comentario"]."<br>"."<br>"; ?>
                <form id="formulario" method="POST" action="?action=eliminarcomentario">
                  <?php
                    $id=$comentario["id"];
                    echo "<input type='hidden' name='id' id='id' value=$id>";
                    echo "<input type='submit' value='Eliminar' >"; ?>
                </form>
            </article> 
          <?php } ?>
        
      <?php } ?> 
      <!--listar contactos-->
      <?php if($CRUD=="listarContactos"){ ?>
        <?php foreach ($contactos as $contacto) {?>
            <article class="text-center"> 
              <?php  
                $autorNegrita=$contacto["nombre"];
                echo "<b>$autorNegrita</b>";  
                echo ": ".$contacto["email"]. " dice: ".$contacto["comentario"]."<br>"."<br>"; ?>
            </article> 
            <?php } ?>
      <?php } ?>  

      <!--Crear Categoria-->
      <?php if($CRUD=="crearCategoria") {?>
        <form id="formulario" method="POST" action="?action=crearCate">
          <?php if($cat==1) echo "Categoría Agregada Exitosamente" ?>
          <div class="form-group">
            <label for="titulo">Nueva Categoría</label>
            <input type='text' class="form-control" id="nuevacategoria" name="nuevacategoria" required="true">
          </div>
          <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
        </form>
      <?php } ?>
      <!--Crear Categoria-->
      <?php if($CRUD=="registrarse") {?>
        <form id="formulario" method="POST" action="?action=registrar">
          <div class="form-group">
            <label for="exampleInputEmail1">Email Address</label>
            <input type="email" class="form-control" id="nombre" name="nombre" required="true">
          </div>
          <div class="form-group">
            <label for="clave">Contraseña</label>
            <input type="password" class="form-control" id="clave" name="clave" required="true">
          </div>
          <button type="submit" class="btn btn-primary">Registrar</button>
          </form>
      <?php } ?>
      <!--Leer/Eliminar/Modificar Categoria-->
      <?php if($CRUD=="leerCategoria"){ ?>
        <form id="formulario" method="POST" action="?action=modificarcat">
          <div class="form-group">
              <label for="categoria">Categoría</label>
              <select class="custom-select" name="categoria" id="categoria">
                <option selected>Seleccione Categoría</option>
                <?php
                  foreach($categorias as $categoria){
                    echo "<option value='".$categoria["id"]."'>".$categoria["categoria"]."</option>";
                  }
                ?>
              </select> 
          </div>
          <button type="submit" class="btn btn-primary">Eliminar</button>
        </form>
      <?php } ?>
    </div>
  </section>

</body>
<!--Pie de pagina-->
<footer id="pie">
 	Copyright @2020
 	<br/>
 	ShiShiGanG
</footer>
</html>