<!DOCTYPE html>
<html lang="es" ng-app="aplicacion">
<head> 
	<!--Meta-->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="esto es una description">
  <meta name="keywords" content="HTML5 CSS,JS">
  <!--Css-->
  <link rel="stylesheet" href="views/css/reset.css">
  <link rel="stylesheet" type="text/css" href="views/css/inicio.css">
  <link rel="stylesheet" href="views/css/contacto.css">
  <!--Bootstrap-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!--Tipos de letras-->
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,300;1,700&display=swap" rel="stylesheet">
  <!--jquerry-->

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
 
  <script src="https://kit.fontawesome.com/9266206c89.js" crossorigin="anonymous"></script>
 
  <!--js-->
  <script src='views/js/funciones.js' type='text/javascript'></script>
    
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.11/angular.min.js"></script>
    <script>

      var angularTodo=angular.module("aplicacion",[]);

      angularTodo.controller("mainController",function($scope,$http){
        $scope.names=[];
        
        $http.get('includes/listarCategorias.php')
        .then(function(response){
          $scope.names=response.data;
          console.log(response.data);

        });
        $scope.Eliminar=function(ide){
          if(confirm("Seguro??")){
            $http.post("includes/funcionEliminar.php",{op:'delete',id:ide})
            .then(function(response){
              console.log(response.data);
              $scope.names.splice(this.$index,1);
           });
          }
        }
});
    </script>
    <!--Titulo-->
  	<title>Shiny-news-Administrador</title>
</head>
<body ng-controller="mainController">
	<!--Cabecera cuerpo-->
	<header id="cabecera">
             <div id='cabecera'><i class="fas fa-plus" id="mas"></i> <i class="fas fa-minus" id="menos"></i><i class="fas fa-adjust" id='tiempo'></i></div>
           <h1>Shiny-News</h1><div class='descripcion'>Ingeniería Web</div>
  </header>
	<!--Barra Navegacion-->
  <ul id="barranav" class="nav">
      <li class="nav-item">
        <a class="nav-link " href="index.php">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="noticias.php?cat=todos">Noticias</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contacto.php">Contacto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="admin.php">Administrador</a>
      </li>
  </ul>  
  <!--CRUD-->
  
  <section>
    <div class='container'>
      <div><p>Bienvenido Administrador</p></div>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href='admin.php'>Crear Noticia</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href='?action=Leer'>Listar/Modificar/Eliminar Noticias</a></li>
        </ol>
      </nav>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href='?action=crearCategoria'>Crear Categoría</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href='?action=leerCategoria'>Listar/Modificar/Eliminar Categorías</a></li>
        </ol>
      </nav>
<!--Pie de pagina--> 
     
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Categoria</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat="dato in names">
            <th scope="row">{{dato.id}}</th>
            <td>{{dato.categoria}}</td>
            <th scope="col"><a href='#' ng-click="Eliminar(dato.id)">[Eliminar]</a></th>
          </tr>
        </tbody>
      </table>
    </div>
  </section>

</body>
<!--Pie de pagina-->
<footer id="pie">
 	Copyright @2020
 	<br/>
 	ShiShiGanG
</footer>
</html>